repos:
  # Python hooks
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        files: ^backend/.*\.py$
        
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        files: ^backend/.*\.py$
        args: ['--config=backend/.flake8']
        
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        files: ^backend/.*\.py$
        additional_dependencies: [types-requests, types-Flask]
        
  # Frontend hooks  
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        files: ^frontend/src/.*\.(ts|tsx|css)$
        
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.49.0
    hooks:
      - id: eslint
        files: ^frontend/src/.*\.(ts|tsx)$
        additional_dependencies:
          - eslint@8.49.0
          - eslint-config-react-app
          - '@typescript-eslint/parser'
          - '@typescript-eslint/eslint-plugin'
          
  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
        
  # Documentation check
  - repo: local
    hooks:
      - id: check-docs
        name: Check documentation
        entry: ./scripts/check-docs.sh
        language: script
        pass_filenames: false
        always_run: true